Task 7
Qumeric/AU-java pull request #11
Opened 2016-12-21 16:39 UTC by Qumeric

2016-12-28 13:12 UTC, yurii-litvinov commented
Тут тоже, нужно написать какой-то конфиг для системы сборки, а то за проблемы со сборкой можно получить -2 балла, это не в Ваших интересах

2016-12-28 13:27 UTC, yurii-litvinov requested changes

2016-12-28 13:27 UTC, yurii-litvinov commented on task7/src/main/java/sp/FirstPartTasks.java
> +      return tracks.stream().mapToInt(Track::getRating).reduce(0, Integer::sum)/tracks.size();
"/" выделяется пробелами

2016-12-28 13:27 UTC, yurii-litvinov commented on task7/src/main/java/sp/FirstPartTasks.java
> +      return stream.reduce(1, (a, b) -> (a*b)%modulo);
И тут, все арифметические операторы надо пробелами выделять

2016-12-28 13:27 UTC, yurii-litvinov commented on task7/src/main/java/sp/Zip.java
> +        } catch (Exception e) {
Лучше ловить более специфические исключения. Может, оно бросило исключение из-за того, что это не zip-архив, а может, это NullPointerException из-за ошибки в коде, и если исключение просто проглатывать, мы об ошибке даже не узнаем (пока она нам половину данных не снесёт)

2016-12-28 13:27 UTC, yurii-litvinov commented on task7/src/test/java/sp/SecondPartTasksTest.java
> +      // Не очень удобно тестить работу с файлами, поэтому проверил руками, надеюсь этого достаточно
А в чём проблема тестов работы с файлами? Я больше скажу, надо даже тесты на задачу с zip-архивами.

2016-12-29 15:54 UTC, Qumeric commented on task7/src/test/java/sp/SecondPartTasksTest.java
> +      // Не очень удобно тестить работу с файлами, поэтому проверил руками, надеюсь этого достаточно
Написал тест, оказалось проблемы действительно нет. Только нужно указать working directory. Для zip писать не стал, все равно там только main (то есть совсем просто не потестить) и в ~20 простых строчек.

2016-12-30 13:42 UTC, yurii-litvinov approved these changes

2017-01-09 12:09 UTC, merged