Task2
Qumeric/AU-java pull request #2
Opened 2016-09-26 08:47 UTC by Qumeric

Пока что без сортировки по первым элементам, сегодня к вечеру будет.

2016-09-26 09:49 UTC, Qumeric commented
Немного накосячил с ветками, надо было отделятся от task1. В следующих задачах буду так делать.

2016-09-27 19:15 UTC, Qumeric commented
Правильно ли добавлять в репозиторий .idea?

2016-10-02 12:56 UTC, yurii-litvinov commented
>Правильно ли добавлять в репозиторий .idea?
Ага, но не все файлы: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

2016-10-02 13:18 UTC, yurii-litvinov requested changes
- лучше делать по одному проекту на задачу, чтобы они могли собираться независимо

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task1/HashTable.java
> +public class HashTable {
Нужен более содержательный комментарий, чем имя автора (это и так в истории гита видно), лучше здесь описать сам класс --- для чего он нужен. И не надо отделять комментарий от класса пустыми строчками.

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task1/HashTable.java
> +        return s.hashCode() % this.capacity;
s.hashCode() может вернуть отрицательное число, что может быть неожиданно для остальной хеш-таблицы.

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task2/Matrix.java
> +
Две пустые строки подряд обычно не одобряются, давайте не будем их писать.

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task2/Matrix.java
> + */
Нужен более содержательный комментарий. Всё, что тут написано, в общем-то, известно из истории коммитов.

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task2/Matrix.java
> +    private int n;
n можно не хранить, матрицы в Java сами знают свой размер (правда, не обязаы быть квадратными, но этот инвариант может обеспечить сам класс Matrix.

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task2/Matrix.java
> +            throw new IllegalArgumentException("n should be an odd positive integer.");
Текст исключения может поставить пользователя в тупик, n-то нигде не упоминается.

2016-10-02 13:18 UTC, yurii-litvinov commented on src/main/java/info/qumeric/task2/Matrix.java
> +        if (matrix[0].length != rowsCount) {
С matrix[0] всё может быть ок, а с matrix[1] уже нет, надо бы все строки проверить.

2016-10-04 15:22 UTC, Qumeric commented
Все замечания из обоих задач пофиксил, кроме хранения n в Matrix -- оставил для удобства.
Еще сделал более адекватную структуру, не хотелось возится, пришлось сделать git `push --force`

2016-10-16 14:44 UTC, closed without merging