Task 5
Qumeric/AU-java pull request #8
Opened 2016-12-21 16:31 UTC by Qumeric

2016-12-28 13:07 UTC, yurii-litvinov commented
А как это собирать? :)

2016-12-28 14:25 UTC, yurii-litvinov requested changes

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function1.java
> +      x = arg;
Здесь и ниже, лучше оборачивать тело if-ов, for-ов и т.д. в фигурные скобки, даже если в теле всего один оператор.

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Collections.java
> +        a – Iterable*/
Это можно было написать у самих методов

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Collections.java
> +      return foldlRec(f, f.apply(acc, it.next()), it);
Для языка без хвостовой рекурсии (например, для Java) это верный способ получить StackOverflowError на хоть сколько-нибудь больших коллекциях (я думаю, 10000 элементов уже будет достаточно)

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function1.java
> +    return this;
Делать это in place --- плохая идея. Я могу захотеть получить две отдельные функции путём композиции двух других функций с одной данной, а получу композицию всех трёх. Кстати, без in place, если не извращаться, а выдавать просто новую функцию, кода будет примерно втрое меньше, потому что не нужны будут поля (вообще) и хитрости с apply и calculate

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function1.java
> +  public Function1 compose (Function1 g) {
Пробел перед скобкой лишний

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function1.java
> +  }
Зачем это? :)

2016-12-28 14:25 UTC, yurii-litvinov commented on task5/src/test/java/info/qumeric/hw/task5/Function1Test.java
> +    assertEquals(3*3, new SquareInteger().bind(3).apply(4));
Арифметические операции выделяются пробелами

2016-12-28 19:37 UTC, Qumeric commented on task5/src/main/java/info/qumeric/hw/task5/Function1.java
> +  }
Для тестов

2016-12-28 19:38 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function1.java
> +  }
Тестовый код имеет смысл убрать в tests

2016-12-30 13:32 UTC, yurii-litvinov requested changes
Поправьте, пожалуйста

2016-12-30 13:32 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function2.java
> +  public Function2 compose (Function1 g) {
Пробел перед скобкой лишний :)

2016-12-30 13:32 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Function2.java
> +  public Function2 bind2(Object y) {
Но ведь функции bind должны возвращать Function1, а не Function2.

2016-12-30 13:32 UTC, yurii-litvinov commented on task5/src/main/java/info/qumeric/hw/task5/Predicate.java
> +  public static Predicate ALWAYS_TRUE() {
Раз это метод, он должен и называться как метод, со строчной

2016-12-30 17:50 UTC, yurii-litvinov approved these changes

2017-01-09 12:09 UTC, merged