Task 6
Qumeric/AU-java pull request #9
Opened 2016-12-21 16:31 UTC by Qumeric

2016-12-28 13:53 UTC, yurii-litvinov requested changes
Тут тоже нужно что-нибудь сделать со сборкой

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +public class MyTreeSetImpl<E extends Comparable<E>> extends AbstractSet<E> implements MyTreeSet<E> {
Не должно быть дополнительного ограничения на E, мы для того и принимаем компаратор, что если натуральный порядок не определён, можно было бы свой компаратор передать

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +  MyTreeSetImpl() {
А чего у него пакетная видимость?

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +   * Reverse elements in set. Works in place and returns this (just for sake of compatibility with {@link MyTreeSet})
Внезапно. Нет, in place --- это плохая идея

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +    Node node = new Node(e);
А если такой узел уже есть, это выделение памяти и потом сборка мусора без какой-либо объективной причины

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +    while(it.hasNext()) {
Между while и "(" нужен пробел, здесь и ниже

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +  }
Ожидалась примерно логарифмическая трудоёмкость, через итератор все могут

2016-12-28 13:53 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +      //}
Закомментированного кода быть не должно

2016-12-29 15:27 UTC, Qumeric commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +  }
Все равно дерево не сбалансированое, так что асимптотически одно и то же. Оставил как есть, остальное все поправил.

2016-12-30 13:40 UTC, yurii-litvinov requested changes

2016-12-30 13:40 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +public class MyTreeSetImpl<E extends Comparable<? super E>> extends AbstractSet<E> implements MyTreeSet<E> {
Я ведь просил, чтобы не было дополнительного ограничения на E. Это половина сложности задачи :) Должно быть так:
```java
public class MyTreeSetImpl<E> extends AbstractSet<E> implements MyTreeSet<E> {
```

2016-12-30 13:40 UTC, yurii-litvinov commented on task6/src/main/java/info/qumeric/hw/task6/MyTreeSetImpl.java
> +  }
Асимптотически кусорт работает за квадрат, давайте всё пузырьком сортировать. Но как хотите, будет -1 балл за такую реализацию, это не так много :)

2026-03-13 13:40 UTC, closed without merging